# Generated by Django 4.1 on 2023-09-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='ice',
        ),
        migrations.AddField(
            model_name='coffee',
            name='stock',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='drink_kind',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.SmallIntegerField(default=0),
        ),
    ]
