# Generated by Django 4.1 on 2023-09-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.SmallIntegerField()),
                ('ice', models.BooleanField()),
                ('drink_kind', models.CharField(max_length=20)),
            ],
        ),
    ]
